//
//  Constants.h
//  ragnarok
//
//  Created by Xiao Xiao on 1/25/13.
//
//

#import <Foundation/Foundation.h>

#define EVENT_CHARACTER_TOUCH @"EVENT_CHARACTER_TOUCH"
#define EVENT_CHARACTER_MOVE @"EVENT_CHARACTER_MOVE"
#define EVENT_CHARACTER_DECIDE_ATTACK @"EVENT_CHARACTER_DECIDE_ATTACK"
#define EVENT_CHARACTER_READY_ATTACK @"EVENT_CHARACTER_READY_ATTACK"
#define EVENT_CHARACTER_DONE_ACTION @"EVENT_CHARACTER_DONE_ACTION"
#define EVENT_CHARACTER_DONE_MOVE @"EVENT_CHARACTER_DONE_MOVE"
#define EVENT_CHARACTER_DONE_ATTACK @"EVENT_CHARACTER_DONE_ATTACK"
#define EVENT_CHARACTER_CANCEL_ACTION @"EVENT_CHARACTER_CANCEL_ACTION"
#define EVENT_CHARACTER_DONE_CANCEL @"EVENT_CHARACTER_DONE_CANCEL"

@interface Constants : NSObject

@end
